services:
  web:
    image: zm377/dentistgpt:stable
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./certs
        target: /etc/nginx/certs
        read_only: true
    environment:
      - NGINX_SSL_CERT=/etc/nginx/certs/fullchain.pem
      - NGINX_SSL_KEY=/etc/nginx/certs/privkey.pem
    restart: always